Database and Table Creation
Jodjojo/jo-learning-Project pull request #11
Opened 2023-07-20 13:54 UTC by Jodjojo

The Table creation organization in the migration file

2023-07-20 16:03 UTC, jsamchineme requested changes
The .env.example file should always remain in the repo. It's a file that communicates the expectation of the .env file which is never checked into version control.

2023-07-22 16:07 UTC, Jodjojo reviewed
Readding the ENV example file

2023-07-22 16:40 UTC, jsamchineme approved these changes

2023-07-22 16:41 UTC, merged

2023-07-22 16:55 UTC, Jodjojo reviewed
Testing slack integration for comments